### ISSUE TITLE
Refresh token request doesn't work, when used with Spring Security OAuth 2.0.7

### ISSUE THREAD

**Issue by bxqgit** [royclarkson/spring-rest-service-oauth#19]
Refresh token request doesn't work, when used with Spring Security OAuth 2.0.7

Server returns:
{"error":"server_error","error_description":"UserDetailsService is required."}

Server log:
TokenEndpoint -> Handling error: IllegalStateException, UserDetailsService is required.

**Comment by mariubog** [comment]
Does regular access token request work for you? 
 Because I have no problem getting refresh token with this request:
`curl -X POST -vu clientapp:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d "refresh_token=ca9c1436-26d3-4121-8905-db77cf1bf4d7&client_id=clientapp&client_secret=123456&grant_type=refresh_token"`

You just have to replace above refresh token according to what you have been granted in your acces token request.

I think you must have to messed something up elsewhere, because I do not think refresh token  even evaluates credentials against `UserDetails` for refreshing token, just `ClientDetails` and your logs show problem with `UserDetails`, again I run the code in this example requesting refresh of the token and everyting worked as desired.

Maybe if you recreate your scenario.

**Comment by mariubog** [comment]
works with 2.0.5 version but with 2.0.7  it crashes  they must have messed something up with getting `userDetailsService` from authetication manager but you can just set `UserDetailsService` by yourselve like this:

```java

@Configuration
	@EnableAuthorizationServer
	protected static class AuthorizationServerConfiguration extends AuthorizationServerConfigurerAdapter {

		private TokenStore tokenStore = new InMemoryTokenStore();

		@Autowired
		@Qualifier("authenticationManagerBean")
		private AuthenticationManager authenticationManager;
		@Autowired
		private CustomUserDetailsService userDetailsService;
		
		
		
		@Override
		public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
			// @formatter:off
			endpoints
				.tokenStore(this.tokenStore)
				.authenticationManager(authenticationManager).userDetailsService(userDetailsService);
			 // @formatter:on
		}

		
...rest pretty much the same

```
it has to be changed obviously in this class : 
https://github.com/royclarkson/spring-rest-service-oauth/blob/master/src/main/java/hello/OAuth2ServerConfiguration.java

you could post on ouath github and ask them why now you have to set it up explicitly, but anyway the way above seem to work.
Tell me if it works in your case so I' ll  post pull request.

**Comment by mariubog** [comment]
I posted full code here:
https://github.com/royclarkson/spring-rest-service-oauth/pull/20

**Comment by royclarkson** [comment]
I think this may be the enhancement where this was changed: https://github.com/spring-projects/spring-security-oauth/issues/401

**Comment by royclarkson** [comment]
@dsyer is this an expected change in 2.0.7, should it be submitted as a bug?

**Comment by dsyer** [comment]
Sort of expected (@rwinch might like to see this as well). The change was to try and lift the `UserDetailsService` out of the global `AuthenticationManager` if there is one - otherwise you have to set it explicitly as in the snippet above (you can even set it to null I think, but it's better to have the protection if you are using refresh tokens). If your app has a custom user details service then there might be an ordering problem that prevents the "lifting" from happening in time.

**Comment by royclarkson** [comment]
@dsyer ok, thanks for the clarification.

**Comment by royclarkson** [comment]
Resolved by #22

**Comment by chauhanvipul87** [comment]
Thank you very much. I tried your solution and working great..

**Comment by ncastrocosta** [comment]
It also worked for me. However, what should I do if I want authentication via LDAP? I already have authentication via LDAP in my WebSecurity configuration.

**Comment by sdziubka** [comment]
Migration to 2.0.5 resolves issue.
Thanks!

**Comment by candyadmin** [comment]
thansks @mariubog  

i use this mthod slove my 'IllegalStateException, UserDetailsService is required.' quetion

**Comment by kmandeville** [comment]
I'm getting the exact same error trying to use refresh token to get an access token using Spring Security Oauth2 1.0.17. Is this bug ONLY fixed in 2.x? Is it possible I'm just missing some configuration?

**Comment by kmandeville** [comment]
I figured it out. I have a @Bean configured that is a UserDetailsService, but my OAuth configuration where I configure an AuthorizationServerEndpointsConfigurer doesn't configure the userDetailsService, it just adds an authentication manager. If I inject my UserDetailsService to this class that sets up the rest of the config and add in setting of the userDetailsService in this Configurer, it all seems to finally work fine. Thanks to a comment from Dave Syer on this SO thread: https://stackoverflow.com/questions/30454480/spring-security-oauth2-2-0-7-refresh-token-userdetailsservice-configuration-us/30775410

**Comment by viktor** [comment]
@mariubog thanks for save the day.. I was doing some auth integrations today.

**Comment by patrickHub** [comment]
Verison 2.0.5.RELEASE works for me. Thanks
